export const fieldsData = [
  { id: "username", label: "Mã nhân viên", type: "text" },
  { id: "fullName", label: "Họ và tên", type: "text" },
  {
    id: "gender",
    label: "Giới tính",
    type: "select",
    options: ["Nam", "Nữ"],
  },
  { id: "dateOfBirth", label: "Ngày sinh", type: "date" },
  { id: "personalEmail", label: "Email", type: "text" },
  { id: "phoneNumber", label: "Số điện thoại", type: "text" },
  { id: "department", label: "Cấp quản lý", type: "text" },
  { id: "jobTitle", label: "Chức vụ", type: "text" },
  { id: "rankName", label: "Hàm (Sĩ quan)", type: "text" },
  { id: "identityBirthPlace", label: "Nơi sinh", type: "text" },
  { id: "identityBirthPlace2", label: "Nguyên quán", type: "text" },
  { id: "currentPlace", label: "Chỗ ở hiện nay", type: "text" },
  {
    id: "identityPlace",
    label: "Nơi đăng ký hộ khẩu thường trú",
    type: "text",
  },
  { id: "ethnicity", label: "Dân tộc", type: "text" },
  { id: "religion", label: "Tôn giáo", type: "text" },
  { id: "education_level", label: "Trình độ văn hóa", type: "text" },
  { id: "doan_tncs_hcm", label: "Kết nạp Đoàn TNCS HCM tại", type: "text" },
  { id: "dang_csvn", label: "Kết nạp Đảng CSVN tại", type: "text" },
];
